api:
  dashboard: true

entryPoints:
  web:
    address: ":80"
    transport:
      respondingTimeouts:
        readTimeout: 5s
        writeTimeout: 10s
        idleTimeout: 30s
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
      encodedCharacters:
        allowEncodedSlash: true
        allowEncodedBackSlash: true
        allowEncodedNullCharacter: true
        allowEncodedSemicolon: true
        allowEncodedPercent: true
        allowEncodedQuestionMark: true
        allowEncodedHash: true
  websecure:
    address: ":443"
    transport:
      respondingTimeouts:
        readTimeout: 5s
        writeTimeout: 30s
        idleTimeout: 90s
    http:
      encodedCharacters:
        allowEncodedSlash: true
        allowEncodedBackSlash: true
        allowEncodedNullCharacter: true
        allowEncodedSemicolon: true
        allowEncodedPercent: true
        allowEncodedQuestionMark: true
        allowEncodedHash: true

providers:
  docker:
    endpoint: "tcp://socket-proxy:2375"
    exposedByDefault: false
  file:
    directory: /config
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      storage: /acme.json
      httpChallenge:
        entryPoint: web

log:
  level: INFO

accessLog: {}
